### PR TITLE
Fix race condition in query cancellation

### LINKED ISSUE #577: pq: canceling statement due to user request
Hello there,

Recently, I've been starting to use context queries, but not everywhere.

And in my CI I see some `pq: canceling statement due to user request` appearing where there was no problem before.

In those cases `ctx.Err()` is nil.

What is that error meaning globally ? Is this a problem in my code that was uncovered by the use of context ?? Or could the context support in pq do wrong things ?

EDIT: I'll try to make a more precise case

### PR DESCRIPTION
**Pull request by tamird**
It was previously possible for context cancellation to interleave with
query execution in such a way that the watcher goroutine would not be
scheduled until after the query which it was meant to watch was
complete, and would end up issueing a cancellation for the subsequent
query.

Fixes #577.

---
This change is [Reviewable](https://reviewable.io/reviews/lib/pq/578)

### CODE REVIEW

File: conn_go18.go [hunk 1]
```diff
@@ -49,41 +51,51 @@ func (cn *conn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx,
...
-	defer can.errRecover(&err)
-
 	w := can.writeBuf(0)
 	w.int32(80877102) // cancel request code
 	w.int32(cn.processID)
 	w.int32(cn.secretKey)
 
 	can.sendStartupPacket(w)
-	_ = can.c.Close()
+	can.sendStartupPacket(w)
```
Comment (mjibson) [inline conn_go18.go]: sendStartupPacket panics on various errors: https://github.com/lib/pq/blob/e4af84aab01e159ca479940dbde304519e8e8811/conn.go#L896

I'm not sure removing the errRecover is safe.

File: conn_go18.go [hunk 2]
```diff
@@ -49,41 +51,51 @@ func (cn *conn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx,
...
+	// Read until EOF to ensure that the server received the cancel.
+	if _, err := io.Copy(ioutil.Discard, can.c); err != nil {
+		return err
```
Comment (mjibson) [inline conn_go18.go]: This will cause can.c.Close to not be run if io.Copy returns an error. Why is it better to do that than ignore the error from io.Copy and always run can.c.Close()?

File: conn_go18.go (hunk 1 above)
Comment (tamird) [inline conn_go18.go]: Lovely, thanks for pointing that out; fixed by having it return an error (and panicking in the existing callers).

File: conn_go18.go (hunk 2 above)
Comment (tamird) [inline conn_go18.go]: Good point, fixed.

File: conn_go18.go [hunk 3]
```diff
@@ -49,41 +51,57 @@ func (cn *conn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx,
...
-	w.int32(cn.processID)
-	w.int32(cn.secretKey)
+		w := can.writeBuf(0)
+		w.int32(80877102) // cancel request code
+		w.int32(cn.processID)
+		w.int32(cn.secretKey)
 
-	can.sendStartupPacket(w)
-	_ = can.c.Close()
+		if err := can.sendStartupPacket(w); err != nil {
```
Comment (mjibson) [inline conn_go18.go]: I don't see how the panics are caught here. `cancel()` is only invoked in a go routine, which means a defer'd recover in another go routine won't see it.

File: conn_go18.go [hunk 4]
```diff
@@ -49,41 +51,57 @@ func (cn *conn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx,
...
+		}
 	}
 	return nil
 }
 
-func (cn *conn) cancel() {
-	var err error
-	can := &conn{}
-	can.c, err = dial(cn.dialer, cn.opts)
+func (cn *conn) cancel() error {
```
Comment (mjibson) [inline conn_go18.go]: Why are we returning errors here at all? They are never used. In case we want them in the future and it's just good practice?

File: conn_go18.go (hunk 3 above)
Comment (tamird) [inline conn_go18.go]: sendStartupPacket no longer panics, though.

File: conn_go18.go (hunk 4 above)
Comment (tamird) [inline conn_go18.go]: Yes, that was my thinking.

File: conn_go18.go (hunk 3 above)
Comment (mjibson) [inline conn_go18.go]: Ah, I didn't see that change cuz no reviewable.

Comment (tamird) [inline conn_go18.go]: Yeah, GH reviews are terrible. Pro tip though: you can just navigate to https://reviewable.io/reviews/lib/pq/578.
