### PR TITLE
ssl: only set "sslrootcert" once

### LINKED ISSUE #570: Concurrent map writes
Hi,

i have faced such issue today:

```
fatal error: concurrent map writes
goroutine 4155 [running]:
runtime.throw(0xb18b1d, 0x15)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420672af0 sp=0xc420672ad0
runtime.mapassign(0xa80880, 0xc4204898c0, 0xc420672c08, 0x0)
	/usr/local/go/src/runtime/hashmap.go:589 +0x2a1 fp=0xc420672b90 sp=0xc420672af0
<PROJECT_PATH>/vendor/github.com/lib/pq.ssl(0xc4204898c0, 0x0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/ssl.go:34 +0x27d fp=0xc420672da0 sp=0xc420672b90
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).ssl(0xc420a178c0, 0xc4204898c0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn.go:1033 +0x40 fp=0xc420672e40 sp=0xc420672da0
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).cancel(0xc420b3a2c0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:81 +0xf2 fp=0xc420672ef0 sp=0xc420672e40
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).(<PROJECT_PATH>/vendor/github.com/lib/pq.cancel)-fm()
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:19 +0x2a fp=0xc420672f08 sp=0xc420672ef0
<PROJECT_PATH>/vendor/github.com/lib/pq.watchCancel.func1(0xece220, 0xc42040f170, 0xc420493400, 0xc4203674a0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:67 +0xc4 fp=0xc420672fc0 sp=0xc420672f08
runtime.goexit()
```

**pq version**: `ba5d4f7a35561e22fbdf7a39aa0070f4d460cfc0`
**postgres version**: `9.2`
**go version**: `1.8`

### PR DESCRIPTION
**Pull request by tamird**
Fixes #570, though I have not been able to write a test for this.

Remove methods on `values`. These methods are not a useful abstraction
and only serve to obscure that the underlying structure is a map. Their
presence is particularly inconvenient in that they promote confusing
empty values with the lack of value.

---
This change is [Reviewable](https://reviewable.io/reviews/lib/pq/573)

### CODE REVIEW

File: ssl.go [hunk 1]
```diff
@@ -15,39 +15,55 @@ import (
...
+				cert, err := ioutil.ReadFile(sslrootcert)
+				if err != nil {
+					panic(err)
+				}
+
+				if ok := tlsConf.RootCAs.AppendCertsFromPEM(cert); !ok {
+					errorf("couldn't parse pem in sslrootcert")
+				}
+			} else {
+				delete(o, "sslrootcert")
```
Comment (cbandy) [inline ssl.go]: iiuc, this has the same problem described in #570. We shouldn't be writing to `o`.

File: ssl.go [hunk 2]
```diff
@@ -15,39 +15,55 @@ import (
...
-		tlsConf.ServerName = o.Get("host")
+		tlsConf.ServerName = o["host"]
 	case "disable":
 		return nil
 	default:
 		errorf(`unsupported sslmode %q; only "require" (default), "verify-full", "verify-ca", and "disable" supported`, mode)
 	}
 
 	sslClientCertificates(&tlsConf, o)
-	sslCertificateAuthority(&tlsConf, o)
```
Comment (cbandy) [inline ssl.go]: This function (or its contents) still need to be invoked when `sslmode` is `verify-ca` or `verify-full`.

**Comment by cbandy** [comment]
I can't tell if it's appropriate to treat `o.Get(...) != ""` the same as `_, ok := o[...]; ok`.

File: ssl.go (hunk 2 above)
Comment (cbandy) [inline ssl.go]: See failing tests `TestSSLVerifyCA` and `TestSSLVerifyFull`.

**Comment by tamird** [comment]
All good points, thanks for your review. I'll update it shortly.

File: ssl.go (hunk 1 above)
Comment (tamird) [inline ssl.go]: I don't think so, because it's now guarded by the presence of a non-empty value, which should only happen once at Dial and not during cancellation.

File: ssl.go (hunk 2 above)
Comment (tamird) [inline ssl.go]: Done.

File: ssl.go (hunk 1 above)
Comment (mjibson) [inline ssl.go]: I agree that this is safe and fixes the bug there because when this function is re-invoked during cancel, `sslrootcert` will have been deleted, and so this branch will not be entered.

**Comment by tamird** [comment]
@cbandy addressed your concrete comments; anything else you'd like to see done before merging?

File: ssl.go [hunk 3]
```diff
@@ -64,13 +68,13 @@ func ssl(o values) func(net.Conn) net.Conn {
...
-	sslkey := o.Get("sslkey")
-	sslcert := o.Get("sslcert")
+	sslkey, sslkeyOK := o["sslkey"]
+	sslcert, sslcertOK := o["sslcert"]
 
 	var cinfo, kinfo os.FileInfo
 	var err error
 
-	if sslcert != "" && sslkey != "" {
+	if sslkeyOK && sslcertOK {
```
Comment (cbandy) [inline ssl.go]: As I understand it, this change breaks compatibility with `libpq` connection strings.

If I'm reading `libpq` source correctly, these settings fallback to the user/home paths when the supplied value is blank:

- [`if (conn->sslcert && strlen(conn->sslcert) > 0) ... else ... "%s/%s", homedir, USER_CERT_FILE`](https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L1036-L1039)
- [`if (conn->sslkey && strlen(conn->sslkey) > 0) ... else ... "%s/%s", homedir, USER_KEY_FILE`](https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L1219-L1222)

File: ssl.go [hunk 4]
```diff
@@ -105,16 +109,15 @@ func sslClientCertificates(tlsConf *tls.Config, o values) {
 
 // sslCertificateAuthority adds the RootCA specified in the "sslrootcert" setting.
 func sslCertificateAuthority(tlsConf *tls.Config, o values) {
-	if sslrootcert := o.Get("sslrootcert"); sslrootcert != "" {
+	if sslrootcert, ok := o["sslrootcert"]; ok {
```
Comment (cbandy) [inline ssl.go]: As I understand it, this change breaks compatibility with `libpq` connection strings.

If I'm reading `libpq` source correctly, the CA certificate is only loaded when this setting is not blank:

- [`if (conn->sslrootcert && strlen(conn->sslrootcert) > 0)`](https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L950-L957)

**Comment by cbandy** [comment]
If compatibility with `libpq` connection strings is a goal, then maybe we should also support the home directory fallback for [`sslrootcert`](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT), `~/.postgresql/root.crt`.

File: ssl.go [hunk 5]
```diff
@@ -15,31 +15,35 @@ import (
...
-		// Note: For backwards compatibility with earlier versions of PostgreSQL, if a
-		// root CA file exists, the behavior of sslmode=require will be the same as
-		// that of verify-ca, meaning the server certificate is validated against the
-		// CA. Relying on this behavior is discouraged, and applications that need
-		// certificate validation should always use verify-ca or verify-full.
-		if _, err := os.Stat(o.Get("sslrootcert")); err == nil {
-			verifyCaOnly = true
-		} else {
-			o.Set("sslrootcert", "")
+		// From http://www.postgresql.org/docs/current/static/libpq- ssl.html:
```
Comment (tamird) [inline ssl.go]: Done.

File: ssl.go (hunk 3 above)
Comment (tamird) [inline ssl.go]: The old code is also incompatible with that `libpq` logic in that `libpq` allows either the certificate or the key to be blank, while this only does the right thing if both are blank.

I'm inclined to "break" compatibility in this way until someone reports that they need it, at which time we should add tests and implement the actual `libpq` behaviour.

File: ssl.go (hunk 4 above)
Comment (tamird) [inline ssl.go]: I think you're right, but as mentioned above, I think this is OK until we get a report of someone relying on this behaviour. WDYT?

Comment (tamird) [inline ssl.go]: Fixed and added a test.

File: ssl.go (hunk 3 above)
Comment (tamird) [inline ssl.go]: Fixed this, I think, though I think tests are going to break and I've not yet explicitly tested the empty string case.

**Comment by tamird** [comment]
Well, in general, `values` definitely promotes bad practices. That said, fixing the regressions you pointed out and adding tests.

**Comment by tamird** [comment]
@cbandy OK, I think this is good to go with new tests exercising the treatment of empty `sslcert` and `sslkey` options.

**Comment by mjibson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssl_test.go, line 44 at r1](https://reviewable.io:443/reviews/lib/pq/573#-KejMy7Voy0WoTQIKtYy:-KejMy7WFlWzxUfD8jO1:bqmtjok) ([raw file](https://github.com/lib/pq/blob/2df7fd4097b0afbbeb771dfd9b5a683177179ba9/ssl_test.go#L44)):*
> ```Go
> 
> func checkSSLSetup(t *testing.T, conninfo string) {
> 	_, err := openSSLConn(t, conninfo)
> ```

Why don't we need to close the db here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/573)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssl_test.go, line 44 at r1](https://reviewable.io:443/reviews/lib/pq/573#-KejMy7Voy0WoTQIKtYy:-KejTdFXpOc4bnQ9WosA:b-ula95q) ([raw file](https://github.com/lib/pq/blob/2df7fd4097b0afbbeb771dfd9b5a683177179ba9/ssl_test.go#L44)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why don't we need to close the db here?
</blockquote></details>

I mean, we do, but it doesn't really matter since a nil error will result in a test failure, and the leaked database handle won't turn up anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/573)*

**Comment by mjibson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssl_test.go, line 44 at r1](https://reviewable.io:443/reviews/lib/pq/573#-KejMy7Voy0WoTQIKtYy:-KejTwgh7n7X7VghLf7T:b2q3orv) ([raw file](https://github.com/lib/pq/blob/2df7fd4097b0afbbeb771dfd9b5a683177179ba9/ssl_test.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I mean, we do, but it doesn't really matter since a nil error will result in a test failure, and the leaked database handle won't turn up anywhere.
</blockquote></details>

Will it remain open on the server until a timeout? When running `go test -count 100 -race` trying to find race conditions I've had the pg server complain about too many connections, so I want to make sure we're closing things correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/573)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ssl_test.go, line 44 at r1](https://reviewable.io:443/reviews/lib/pq/573#-KejMy7Voy0WoTQIKtYy:-KejUK-JxFp147trbwAq:bjtwhnk) ([raw file](https://github.com/lib/pq/blob/2df7fd4097b0afbbeb771dfd9b5a683177179ba9/ssl_test.go#L44)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Will it remain open on the server until a timeout? When running `go test -count 100 -race` trying to find race conditions I've had the pg server complain about too many connections, so I want to make sure we're closing things correctly.
</blockquote></details>

There will never be a non-nil connection here in a passing test run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lib/pq/573)*

**Comment by mjibson** [comment]
Well then LGTM, again. I agree that there is (was?) a problem since empty strings had their meaning changed in this PR. It seems like this code handles those in at least a well documented way, and if there are missing combinations we can add those as test cases.

**Comment by tamird** [comment]
Thanks, @mjibson. I'll wait for final approval from @cbandy or else merge this tomorrow.
